name: AWS Lambda Zip Deploy - Python
author: Qubitro
description: Zip deploy to AWS Lambda with requirements in a separate layer.
inputs:
  platform:
    description: the platform that pip should build/retrieve for
    required: true
  lambda_region:
    description: the region of your lambda
    required: true
    default: 'ca-central-1'
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  lambda_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.lambda_layer_arn }}
    - ${{ inputs.lambda_function_name }}
    - ${{ inputs.lambda_region }}
    - ${{ inputs.platform }}
branding:
  icon: 'cloud-lightning'
  color: 'white'
